### PR TITLE
linter: improve method_exists handling

### LINKED ISSUE #362: Improve detection with class_exists/method_exists cases
I use that kind of checks (with `class_exists`+`method_exists` combo) regularly in my libraries to decide what algorithm to use. And i don't want to use `-exclude-checks` because it skips really bad cases in project.

## Installation and steps to reproduce

```bash
# I'm using osx
brew install go
# Installing noverify
mkdir -p $GOPATH/github.com/VKCOM
git clone https://github.com/VKCOM/noverify.git $GOPATH/github.com/VKCOM
cd $GOPATH/src/github.com/VKCOM/noverify
make install
# Use it as a static linter
cd /path/to/symfony3/project
noverify -exclude='vendor/|tests/|tmp/|var/' .
```

## Code Example

For example, this is what i've found after checking in my Symfony v3 project in file `bootstrap.php`:

```php
$path = dirname(__DIR__).'/.env';

if (!class_exists(Dotenv::class)) {
    throw new RuntimeException('Please run "composer require symfony/dotenv" to load the ".env" files configuring the application.');
}

$dotenv = new Dotenv();
if (method_exists($dotenv, 'loadEnv')) {
    $dotenv->loadEnv($path); // <–– Critical is here
}
```

## Actual Behavior

```
<critical> ERROR   undefined: Call to undefined method {\Symfony\Component\Dotenv\Dotenv}->loadEnv() at /path/to/symfony3/project/app/bootstrap.php:9
        $dotenv->loadEnv($path);
                 ^^^^^^^
```

## Expected Behavior

No error here must be :-)

### PR DESCRIPTION
**Pull request by quasilyte**
We collect a slice of `<object, methodName>` pairs
inside a block context.

New pair entries are added via `method_exists(object, methodName)`
upon the if statement entry. These entries are removed
upon that if statement exit.

This new addition does not affect the type inference.
We only permit calling method_exists-defined methods,
but their types will be `(...mixed)->mixed`.

Fixes #362

Signed-off-by: Iskander Sharipov <quasilyte@gmail.com>

Should be merged after #363 is resolved.

### CODE REVIEW

File: src/linter/block.go [hunk 1]
```diff
@@ -1471,6 +1475,18 @@ type andWalker struct {
 
 func (a *andWalker) EnterNode(w walker.Walkable) (res bool) {
 	switch n := w.(type) {
+	case *expr.FunctionCall:
+		args := n.ArgumentList.Arguments
+		nm, ok := n.Function.(*name.Name)
+		if ok && meta.NameToString(nm) == `method_exists` && len(args) == 2 {
```
Comment (YuriyNasretdinov) [inline src/linter/block.go]: I would suggest to use NameEquals to avoid unnecessary allocations in hot paths

Comment (quasilyte) [reply src/linter/block.go]: Maybe we can re-write NameEquals to be more efficient?

I think it also does allocations (it does strings.Split which allocates a slice).

Comment (quasilyte) [reply src/linter/block.go]: Right now it doesn't seem to be faster:
```
BenchmarkNameEquals-8  13470901 79.3 ns/op 16 B/op  1 allocs/op
BenchmarkToString-8    19985751 59.1 ns/op 16 B/op  1 allocs/op
```
```go
var theName = &name.Name{
	Parts: []node.Node{
		&name.NamePart{Value: `method_exists`},
	},
}

func BenchmarkNameEquals(b *testing.B) {
	for i := 0; i < b.N; i++ {
		_ = NameEquals(theName, `method_exists`)
	}
}

func BenchmarkToString(b *testing.B) {
	for i := 0; i < b.N; i++ {
		_ = NameToString(theName) == `method_exists`
	}
}
```

Comment (YuriyNasretdinov) [reply src/linter/block.go]: You're probably right, we need to optimise NameEquals if it does allocate memory. The reason why I still think that we should use NameEquals is that once we do optimise it, all the code that uses it will become faster. If we always use NameToString we can only optimise the use-case where there is only part. If there are two parts, for example, memory allocation will still be required.

**Comment by quasilyte** [comment]
It has the same problems as other if-related contexts.
I think it doesn't hurt much to merge this and then fix #363 with tests that cover all affected linter parts.
