### PR TITLE
fixed plus (+) operator type inference for arrays

### LINKED ISSUE #246: Fix `+` operator type inference
https://www.php.net/manual/en/language.operators.array.php

In PHP, `+` also works for arrays.
It performs union operation and the result type should be inferred as `mixed[]`.
Now it inferred as `int` or `float`.

https://github.com/VKCOM/noverify/blob/fd68c0fe476187de6312548fb9155c69a03a89b9/src/solver/exprtype.go#L315-L316

`+` should be handled a little bit differently than other arithmetical operations.

### PR DESCRIPTION
**Pull request by whisk**
Should fix #246

### CODE REVIEW

File: src/solver/exprtype.go [hunk 1]
```diff
@@ -14,13 +14,23 @@ import (
...
 		return meta.NewTypesMap("int")
 	}
 	return meta.NewTypesMap("float")
 }
 
+// binaryPlusOpType is a special case as "plus" is also used for array union operation
+func binaryPlusOpType(sc *meta.Scope, cs *meta.ClassParseState, left, right node.Node, custom []CustomType) *meta.TypesMap {
+	// TODO: PHP will raise fatal error if one operand is array and other is not, so we may check it too
+	if ExprTypeLocalCustom(sc, cs, left, custom).IsArray() && ExprTypeLocalCustom(sc, cs, right, custom).IsArray() {
+		return meta.NewTypesMap("mixed[]")
```
Comment (YuriyNasretdinov) [inline src/solver/exprtype.go]: You might want to return a union of concrete types here instead so that information about types isn't lost

File: src/meta/typesmap.go [hunk 2]
```diff
@@ -311,6 +311,11 @@ func (m *TypesMap) IsEmpty() bool {
 	return len(m.m) == 0
 }
 
+// Equals check if two typesmaps are the same
+func (m *TypesMap) Equals(m2 *TypesMap) bool {
```
Comment (YuriyNasretdinov) [inline src/meta/typesmap.go]: This is a very inefficient way to compare types.

File: src/solver/exprtype.go (hunk 1 above)
Comment (YuriyNasretdinov) [reply src/solver/exprtype.go]: I would still suggest that you return the _union_ of the types (there is a MergeTypesMap method that does that) instead of using mixed.

Imagine the following (correct) PHP code:

<?php
class A { public function doSomething() { } }
class B { public function doSomething() { } }

$arrA = [ 'a' => new A(); ];
$artB = [ 'b' => new B(); ];
$arrUnion = $arrA + $arrB;

$arrA['a']->doSomething(); // no error
$arrB['b']->doSomething(); // no error
$arrUnion['a']->doSomething(); // this will be "no such method" mixed->doSomething () if you didn't merge the types

Comment (whisk) [reply src/solver/exprtype.go]: MergeTypesMap returns "int[]|string[]" for [1] + ["foo"], which is wrong. Correct type for this union should be (int|string)[].

Not sure if code supports "(A|B)[]" types yet.

Comment (YuriyNasretdinov) [reply src/solver/exprtype.go]: You're right but this is how noverify works right now. It currently does treat a[]|b[] as (a|b)[] anyway

File: src/meta/typesmap.go (hunk 2 above)
Comment (whisk) [reply src/meta/typesmap.go]: Should be fixed.

Comment (YuriyNasretdinov) [reply src/meta/typesmap.go]: m can also be nil. There are no checks for this in String() method probably just because I didn't use it anywhere (it is there for debugging purposes but there is comment about that sadly).

Comment (YuriyNasretdinov) [reply src/meta/typesmap.go]: You can iterate nil maps and get their length (it will be 0). So you only need to check that m or m2 are nil. Two empty type sets can be equal as well so it's even incorrect to return false when they are nil. Also m.m will still cause panic if m is nil.

Comment (whisk) [reply src/meta/typesmap.go]: Updated. As of #257 we are not using pointers here which simplifies things a little.

**Comment by quasilyte** [comment]
:tada:
